# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Hello_World
      run: docker run hello-world

    - name: Build-DB
      run: docker-compose build

    - name: Create-DB
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go

  build:
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v4

      - name: Build
        run: go build -v main.go
